/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author dougl
 */
public class RadioButton extends javax.swing.JFrame {

    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcaoEnvio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pac = new javax.swing.JRadioButton();
        encomendaNormal = new javax.swing.JRadioButton();
        sedex = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnLimparSelecao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelOpcaoSelecionada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exemplo de uso de Radio Button");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 1, true), "Escolha uma opção de envio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.Color.white)); // NOI18N

        pac.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroupOpcaoEnvio.add(pac);
        pac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pac.setForeground(new java.awt.Color(255, 255, 255));
        pac.setText("PAC");
        pac.setActionCommand("pac");
        pac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacActionPerformed(evt);
            }
        });

        encomendaNormal.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroupOpcaoEnvio.add(encomendaNormal);
        encomendaNormal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        encomendaNormal.setForeground(new java.awt.Color(255, 255, 255));
        encomendaNormal.setText("Encomenda normal");
        encomendaNormal.setActionCommand("encomenda normal");
        encomendaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encomendaNormalActionPerformed(evt);
            }
        });

        sedex.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroupOpcaoEnvio.add(sedex);
        sedex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sedex.setForeground(new java.awt.Color(255, 255, 255));
        sedex.setText("SEDEX");
        sedex.setActionCommand("sedex");
        sedex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sedex)
                    .addComponent(encomendaNormal)
                    .addComponent(pac))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pac)
                .addGap(18, 18, 18)
                .addComponent(encomendaNormal)
                .addGap(18, 18, 18)
                .addComponent(sedex)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnLimparSelecao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimparSelecao.setText("Limpar seleção");
        btnLimparSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSelecaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Opção selecionada:");

        labelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelValor.setText("Aguardando seleção");

        labelOpcaoSelecionada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelOpcaoSelecionada.setText("Você escolheu...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOpcaoSelecionada)
                            .addComponent(labelValor)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnLimparSelecao)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelValor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelOpcaoSelecionada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLimparSelecao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacActionPerformed
        labelValor.setText("R$ 20,00");
        labelOpcaoSelecionada.setText(buttonGroupOpcaoEnvio.getSelection().getActionCommand());
    }//GEN-LAST:event_pacActionPerformed

    private void encomendaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encomendaNormalActionPerformed
        labelValor.setText("R$ 10,00");
        labelOpcaoSelecionada.setText(buttonGroupOpcaoEnvio.getSelection().getActionCommand());
    }//GEN-LAST:event_encomendaNormalActionPerformed

    private void sedexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedexActionPerformed
        labelValor.setText("R$ 50,00");
        labelOpcaoSelecionada.setText(buttonGroupOpcaoEnvio.getSelection().getActionCommand());
    }//GEN-LAST:event_sedexActionPerformed

    private void btnLimparSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSelecaoActionPerformed
        labelValor.setText("Aguardando seleção");
        labelOpcaoSelecionada.setText("Você escolheu...");
        buttonGroupOpcaoEnvio.clearSelection();
    }//GEN-LAST:event_btnLimparSelecaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparSelecao;
    private javax.swing.ButtonGroup buttonGroupOpcaoEnvio;
    private javax.swing.JRadioButton encomendaNormal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelOpcaoSelecionada;
    private javax.swing.JLabel labelValor;
    private javax.swing.JRadioButton pac;
    private javax.swing.JRadioButton sedex;
    // End of variables declaration//GEN-END:variables
}
